SELECT
    NAME,
    DATETIME
FROM ANIMAL_INS
WHERE (ANIMAL_ID, NAME) NOT IN (
    SELECT
        I.ANIMAL_ID,
        I.NAME
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
)
ORDER BY DATETIME ASC
LIMIT 3

